In [1]:
#Google's Second Price Auction
#Step1=Bid*CTR= adrank
def adrank(bid,ctr):
    ad=bid*ctr
    return ad

In [2]:
adrank(4,0.07)

0.28

In [3]:
#to calculate paid for rank1= BID2*ctr2/ctr1

In [4]:
def paid(Bid,ctr2,ctr1):
    value=Bid*(ctr2/ctr1)
    return value

In [5]:
paid(3,0.08,0.07)

3.4285714285714284

In [6]:
import pandas as pd
import re

In [10]:
filenames=["page1.html","page2.html","page3.html","page4.html","page5.html"]

In [11]:
index=0
pages={}

for filename in filenames:
    with open(filename,"r", encoding="latin-1")as f:
        pages["page_"+str(index)]=f.read()
        index+=1
        
page_0=pages["page_0"]
page_1=pages["page_1"]
page_2=pages["page_2"]
page_3=pages["page_3"]
page_4=pages["page_4"]

In [12]:
pages.keys()

dict_keys(['page_0', 'page_1', 'page_2', 'page_3', 'page_4'])

In [13]:
def zone_parser(pages):
    tags= ["<br>","\n","<p>","</p>","</b>","<i>","</i>","<r>","<h3>","<h3>"]
    parsed_pages={}
    i=0
    
    for page in pages.values():
        parsed_page= {}
        
        #parse the title
        title_start= page.find("<title>")
        title_end= page.find("</title>")
        title= page[title_start+7:title_end]
        
        for tag in tags:
            title= title.replace(tag, "")
        
        parsed_page['title']= title
        
        #Parse the abstract
        abstract_start= page.lower().find("abstract")
        abstract= page[abstract_start+14:]
        abstract_end= abstract.find('\n\n')
        abstract= abstract[:abstract_end]
        
        for tag in tags:
            abstract= abstract.replace(tag,"")
        #abstract= re.sub(' +', ' ', abstract)
        parsed_page['abstract']= abstract
        
        #Parse the introduction:
        intro_start= page.lower().find("<h2>")
        intro= page[intro_start:]
        intro_heading_end= intro.find("</h2>")
        intro= intro[intro_heading_end+25:]
        intro_end= intro.lower().find("<h2>",10)
        intro= intro[:intro_end]
        
        for tag in tags:
            intro= intro.replace(tag," ")
        intro=re.sub(' +',' ',intro)
        parsed_page['introduction']= intro
        
        parsed_pages['page_'+str(i)]= parsed_page
        i+=1
        
    return parsed_pages

In [14]:
parsed_pages= zone_parser(pages)
print(parsed_pages['page_3']['introduction'])

 Many computer users are switching from personal computers to smartphones or tablets for their daily computing needs. This transition has created growth in mobile application development, with many companies offering exclusive services and promotions over their mobile apps. The goal is to lure users to smartphones. And the rewards are huge. Since launching the App Store in 2008, Apple's developer community has earned $70 billion worldwide, with $20 billion in 2016 alone [12, 13]. Furthermore, gaming is the top-grossing across 25 app categories, with games accounting for 25% of all available apps [20]. This paper focuses on input methods for mobile games. Smartphones receive input through a touchscreen, a camera, microphone, accelerometer, etc. Touch input is the primary input method on smartphones, and this is also true for mobile games. Some drawbacks of touch input for the player are lack of tactile feedback and occlusion of the display [8]. Smartphones and tablets typically include an accelerometer which measures the tilting motion and the physical orientation of the device. Device orientation can be used for controlling game objects. Such control, commonly called "tilt", is widely used as an input method in mobile games. In addition, a smartphone's camera can track movement in the real world. Using the front-facing camera, we can track the user's face or eye, and even obtain their facial expression. Thus, eye-tracking and head-tracking are possible input methods for hands-free games, in addition to tilt. One benefit of hands-free input is to provide more entertainment options for people with special needs. However, using the eyes as an input method is problematic, since the eyes are also our main perception method [16]. Notably, ease of use and novelty has an impact on "perceived enjoyment" in mobile games [18]. With iOS 11, Apple introduced ARKit, a framework for creating Augmented Reality (AR) apps for the <I>iPhone</I> and <I>iPad</I>. ARKit combined with the TrueDepth front-facing camera available on the <I>iPhone X</I> enables face or eye tracking in AR apps. The TrueDepth camera gives the position, orientation, and expression of the face in real-time. It also enables Face ID, the facial recognition method for authentication on an <I>iPhone X</I>. In this paper, we evaluate the functionality of eye-tracking and head-tracking, using ARKit and the TrueDepth camera. We compare tilt-input, head-tracking, and eye-tracking for a custom-designed game called <I>TrackMaze</I>. With <I>TrackMaze</I>, the player navigates a virtual ball through a static maze. We address several questions: Is it possible to use eye-tracking and head-tracking for mobile games that need whole-display navigation? Can eye-tracking and head-tracking result in better perceived enjoyment? Can eye-tracking or head-tracking compete with tilt-input, the natural input method for maze games? Which input method is easiest to use? Do users prefer one input method over the others? In the next section, we review studies on mobile games related to tilt-input, eye-tracking, and head tracking. Then, we discuss the methodology and results of our user study. We then offer conclusions on user performance and enjoyment for tilt, eye-tracking, and head-tracking as input methods.

In [15]:
from collections import Counter

In [16]:
token_counts= {}
for key in parsed_pages.keys():
    page_counts={}
    for k, v in parsed_pages[key].items():
        #replace punctuation
        punct= ['.','?','!',':',';',',','(',')','-']
        v= v.lower()
        
        for p in punct:
            v= v.replace(p, "")
# to get the ans add empty space above       
        tokens= v.split(' ')
        cnt= Counter(tokens)
        page_counts[k]= cnt
        
    token_counts[key]= page_counts

In [17]:
zone_index= pd.DataFrame.from_dict({(i,j): token_counts[i][j] for i in token_counts.keys() for j in token_counts[i].keys()}, orient='index').fillna(0)

In [18]:
zone_index

                     auditory   and  visual  feedback  during   eye  typing  \
page_0 title              1.0   1.0     1.0       1.0     1.0   1.0     1.0
       abstract           1.0   3.0     1.0       3.0     0.0   2.0     2.0
page_1 abstract           2.0   4.0     2.0       5.0     0.0   2.0     5.0
page_0 introduction       0.0   6.0    11.0       8.0     1.0   3.0     3.0
page_1 title              0.0   2.0     0.0       1.0     0.0   1.0     1.0
       introduction       0.0  12.0     1.0       4.0     2.0  14.0    10.0
page_2 abstract           0.0   5.0     0.0       0.0     0.0   0.0     0.0
       introduction       0.0   5.0     0.0       1.0     0.0   0.0     0.0
page_3 title              0.0   1.0     0.0       0.0     0.0   0.0     0.0
       abstract           0.0   8.0     0.0       0.0     0.0   0.0     0.0
       introduction       0.0  20.0     0.0       1.0     0.0   2.0     0.0
page_4 abstract           0.0   4.0     0.0       0.0     0.0   3.0     0.0
       introduction       0.0  15.0     1.0       0.0     0.0  10.0     0.0
       title              0.0   0.0     0.0       0.0     0.0   1.0     0.0
page_2 title              0.0   0.0     0.0       0.0     0.0   0.0     0.0

                     r>we  describe     a  ...  comparing  baseline   ie  \
page_0 title          0.0       0.0   0.0  ...        0.0       0.0  0.0
       abstract       1.0       1.0   2.0  ...        0.0       0.0  0.0
page_1 abstract       0.0       0.0   1.0  ...        0.0       0.0  0.0
page_0 introduction   0.0       0.0   2.0  ...        0.0       0.0  0.0
page_1 title          0.0       0.0   0.0  ...        0.0       0.0  0.0
       introduction   0.0       0.0  18.0  ...        0.0       0.0  0.0
page_2 abstract       0.0       0.0   2.0  ...        0.0       0.0  0.0
       introduction   0.0       0.0   6.0  ...        0.0       0.0  0.0
page_3 title          0.0       0.0   1.0  ...        0.0       0.0  0.0
       abstract       0.0       0.0   4.0  ...        0.0       0.0  0.0
       introduction   0.0       0.0   7.0  ...        0.0       0.0  0.0
page_4 abstract       0.0       0.0   6.0  ...        0.0       0.0  0.0
       introduction   0.0       0.0   9.0  ...        1.0       1.0  1.0
       title          0.0       0.0   0.0  ...        0.0       0.0  0.0
page_2 title          0.0       0.0   0.0  ...        0.0       0.0  0.0

                     determine  rest  organized  described  discussed  \
page_0 title               0.0   0.0        0.0        0.0        0.0
       abstract            0.0   0.0        0.0        0.0        0.0
page_1 abstract            0.0   0.0        0.0        0.0        0.0
page_0 introduction        0.0   0.0        0.0        0.0        0.0
page_1 title               0.0   0.0        0.0        0.0        0.0
       introduction        0.0   0.0        0.0        0.0        0.0
page_2 abstract            0.0   0.0        0.0        0.0        0.0
       introduction        0.0   0.0        0.0        0.0        0.0
page_3 title               0.0   0.0        0.0        0.0        0.0
       abstract            0.0   0.0        0.0        0.0        0.0
       introduction        0.0   0.0        0.0        0.0        0.0
page_4 abstract            0.0   0.0        0.0        0.0        0.0
       introduction        1.0   1.0        1.0        1.0        1.0
       title               0.0   0.0        0.0        0.0        0.0
page_2 title               0.0   0.0        0.0        0.0        0.0

                     finally    4
page_0 title             0.0  0.0
       abstract          0.0  0.0
page_1 abstract          0.0  0.0
page_0 introduction      0.0  0.0
page_1 title             0.0  0.0
       introduction      0.0  0.0
page_2 abstract          0.0  0.0
       introduction      0.0  0.0
page_3 title             0.0  0.0
       abstract          0.0  0.0
       introduction      0.0  0.0
page_4 abstract          0.0  0.0
       introduction      1.0  1.0
       title             0.0  0.0
page_2 title             0.0  0.0

[15 rows x 997 columns]

In [19]:
zone_index.index.names= ['page','zone']

In [20]:
title_eye= zone_index.query('(zone == "title" & eye > 0)')['eye']
abstract_performance= zone_index.query('(zone == "abstract" & performance > 0)')['performance']
intro_method= zone_index.query('(zone == "introduction" & method > 0)')['method']

In [21]:
title_eye.index= title_eye.index.droplevel(level=1)
abstract_performance.index= abstract_performance.index.droplevel(level=1)
intro_method.index= intro_method.index.droplevel(level=1)

In [22]:
matches= title_eye.index.intersection(abstract_performance.index).intersection(intro_method.index)

In [23]:
print(len(matches))
for page in matches: 
    print(page)
# to get the ans add empty space above

0

# Weighted zone score

In [24]:
score_df= zone_index[['eye','tracking']].transpose()

In [25]:
score_df= score_df.applymap(lambda x: 1 if x>0 else 0)
score_df.loc[:, (slice(None), 'abstract')]

page       page_0   page_1   page_2   page_3   page_4
zone     abstract abstract abstract abstract abstract
eye             1        1        0        0        1
tracking        0        0        0        0        1

In [26]:
score_df.loc[:, (slice(None),'title')]= score_df.loc[:, (slice(None), 'title')]* 0.45
score_df.loc[:, (slice(None),'abstract')]= score_df.loc[:, (slice(None), 'abstract')]* 0.3
score_df.loc[:, (slice(None),'introduction')]= score_df.loc[:, (slice(None), 'introduction')]* 0.25

In [27]:
score_df.transpose()

                      eye  tracking
page   zone
page_0 title         0.45      0.00
       abstract      0.30      0.00
page_1 abstract      0.30      0.00
page_0 introduction  0.25      0.00
page_1 title         0.45      0.00
       introduction  0.25      0.25
page_2 abstract      0.00      0.00
       introduction  0.00      0.00
page_3 title         0.00      0.00
       abstract      0.00      0.00
       introduction  0.25      0.25
page_4 abstract      0.30      0.30
       introduction  0.25      0.25
       title         0.45      0.45
page_2 title         0.00      0.00

In [28]:
score_df= score_df.transpose().groupby('page').sum()

In [29]:
score_df

         eye  tracking
page
page_0  1.00      0.00
page_1  1.00      0.25
page_2  0.00      0.00
page_3  0.25      0.25
page_4  1.00      1.00

In [30]:
score_df['weighted_zone_score']= score_df['eye']+score_df['tracking']

In [31]:
score_df=score_df.sort_values(by= 'weighted_zone_score', ascending= False)

In [32]:
score_df

         eye  tracking  weighted_zone_score
page
page_4  1.00      1.00                 2.00
page_1  1.00      0.25                 1.25
page_0  1.00      0.00                 1.00
page_3  0.25      0.25                 0.50
page_2  0.00      0.00                 0.00

In [33]:
score_df.columns

Index(['eye', 'tracking', 'weighted_zone_score'], dtype='object')

In [34]:
score_df=score_df.drop(columns=['eye','tracking'])

In [35]:
score_df

        weighted_zone_score
page
page_4                 2.00
page_1                 1.25
page_0                 1.00
page_3                 0.50
page_2                 0.00